services:
  db:
    image: postgres:17
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: tascal
      POSTGRES_PASSWORD: tascal
      POSTGRES_DB: tascal
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
